package org.highwaycinemaplanner;

public enum ScheduleMovieStatus {
    MOVIE_NOT_FOUND_IN_CATALOG,
    MOVIE_SCHEDULED,
    NO_ROOMS_AVAILABLE_AT_GIVEN_TIME,
    MOVIE_OUTSIDE_OF_CINEMA_WORKING_HOURS,
    MOVIE_OUTSIDE_OF_CINEMA_PREMIERE_HOURS,
    NO_ROOMS_IN_CINEMA
}